
spring:
  application:
    name: portfolio-service

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/place?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      #        javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        #Hibernate Full Text search
        dialect: org.hibernate.dialect.MySQL8Dialect
        type: trace
        dialect.storage_engine: innodb
      hibernate.search:
        backend:
          type: lucene
          lucene_version: LATEST
          analysis.configurer: luceneAnalysisConfiguration
          directory.root: opt/indexes

server:
  port : 8090
  forward-headers-strategy: framework
  error:
    include-message: always
  http2:
    enabled: true
  tomcat:
    threads:
      max: 5
      min-spare: 1


